; ============================================================================
; sid-wrapper.s - Generic SID file wrapper for any conforming sound source
; ============================================================================
;
; Assembles a sound source into a standalone build suitable for wrapping in a
; PSID v2 SID file. Works with any source that conforms to the sound API
; contract (see below).
;
; The sound source to include is selected at build time via sound-select.inc,
; a one-line file generated by build-sid.py. SID_BUILD=1 is also defined
; so sound sources can adapt their build for standalone use if needed.
;
; All segments (SOUND_LO, SCREEN_BUFFER, SOUND_HI, SID_STUB) are placed
; contiguously at a configurable base address by the linker. Since all
; conforming engines use label-based references, the result is relocatable.
;
; Build: assembled by build-sid.py via ca65/ld65 with sid.cfg
;
; ============================================================================
; Sound API Contract
; ============================================================================
;
; Any sound source included here must export the following symbols:
;
; Entry points:
;   sound_init              JSR - Initialize SID chip and engine state
;   sound_update            JSR - Frame update (called at 50Hz from IRQ)
;   music_start             JSR - Start a song (Y = song_xxx - music_song_table)
;   sfx_start               JMP - Credits SFX handler (may be a stub RTS)
;
; Song table (base + 12 named offsets):
;   music_song_table        Base address for Y-offset computation
;   song_level_theme        song_level_resume       song_level_final
;   song_bonus_round        song_game_over          song_level_complete
;   song_extend             song_title_screen       song_hurry_up
;   song_round_start        song_super_bonus        song_ending
;
; SFX presets (may be stubs):
;   sfx_preset_0 .. sfx_preset_5
;
; Capability flag (compile-time constant):
;   SOUND_SONGS_LOOP        0 = songs end naturally, 1 = songs loop forever
;
; Segment boundary labels:
;   L_7040                  Start of SOUND_LO content
;   musichandlers_end       End of SOUND_LO content
;   title_music_voice0      Start of SCREEN_BUFFER content
;   screen_buffer_end       End of SCREEN_BUFFER content
;   music_control_data      Start of sound state (zeroed by wrapper on init)
;   music_control_data_end  End of sound state
;
; Segments used (sizes for game build):
;   SOUND_LO                $0400 bytes max
;   SCREEN_BUFFER           $02E0 bytes max
;   SOUND_HI                $0C50 bytes max (page-aligned by linker)
;
; Implicit zero-page contract:
;   SYESSION ($A4)          Nonzero while playing, zero when idle/finished
;
; ============================================================================

.setcpu "6502"

; ============================================================================
; External symbol definitions
; ============================================================================
; Union of all zero-page locations used by any conforming sound source.
; The original sound.s uses all of these. Other conforming sources may
; use a subset. Unused definitions are harmless.

; --- SID Chip (Sound Interface Device) ---
SID_V1_FREQ_LO = $D400         ; Voice 1 frequency low byte
SID_V1_FREQ_HI = $D401         ; Voice 1 frequency high byte
SID_V1_PW_LO   = $D402         ; Voice 1 pulse width low byte
SID_V1_PW_HI   = $D403         ; Voice 1 pulse width high byte
SID_V1_CTRL    = $D404          ; Voice 1 control register
SID_FILT_LO    = $D415         ; Filter cutoff frequency low bits
SID_FILT_HI    = $D416         ; Filter cutoff frequency high byte
SID_VOL        = $D418         ; Volume and filter mode control

; --- Zero-page locations ---
CHRGOT      = $79               ; Temp storage (sound engine)
TXTPTR      = $7A               ; Text pointer / temp storage
STATUS      = $90               ; I/O status byte
STKEY       = $91               ; Keyboard buffer pointer
SVXT        = $92               ; Temp storage (voice state)
BESSION     = $95               ; Temp storage (voice state)
DFLTN       = $98               ; Temp storage (voice state)
TESSION     = $9B               ; Temp storage (voice state)
TIME        = $9E               ; Temp storage / music data pointer
BSOUR       = $A3               ; Temp storage (sound engine)
SYESSION    = $A4               ; Voice-active flag (0=idle, nonzero=playing)

; ============================================================================
; Include the sound source
; ============================================================================
; The sound source to include is selected at build time via sound-select.inc,
; a one-line file generated by build-sid.py (or the Makefile) containing:
;   .include "sound.s"          (or whichever sound source is selected)

.include "sound-select.inc"

; ============================================================================
; SID player stubs (SID_STUB segment)
; ============================================================================

        .segment "SID_STUB"

.export sid_init, sid_play

NUM_SONGS = 12

; --- Song Y-value lookup table ---
; Maps PSID song index (0-based) to the Y parameter for music_start.
; Each entry is (song_xxx - music_song_table), computed at assembly time.
song_table:
        .byte   song_level_theme    - music_song_table ; Song 1:  Main level theme
        .byte   song_level_resume   - music_song_table ; Song 2:  Level resume
        .byte   song_level_final    - music_song_table ; Song 3:  Level 99 theme
        .byte   song_bonus_round    - music_song_table ; Song 4:  Bonus round
        .byte   song_game_over      - music_song_table ; Song 5:  Game over
        .byte   song_level_complete - music_song_table ; Song 6:  Level complete
        .byte   song_title_screen   - music_song_table ; Song 7:  Title screen
        .byte   song_extend         - music_song_table ; Song 8:  EXTEND fanfare
        .byte   song_hurry_up       - music_song_table ; Song 9:  Hurry-up
        .byte   song_round_start    - music_song_table ; Song 10: Round start
        .byte   song_super_bonus    - music_song_table ; Song 11: Super bonus
        .byte   song_ending         - music_song_table ; Song 12: Ending

; Music state size (derived from sound source exports)
MUSIC_STATE_ADDR = music_control_data
MUSIC_STATE_SIZE = music_control_data_end - music_control_data

; --- sid_init ---
; Called by the PSID driver. A = song number (0-based per PSID spec).
;
; Steps:
;   1. Zero engine music state
;   2. Call sound_init
;   3. Look up song Y-value, call music_start
sid_init:
        ; Save song number
        tax
        cpx     #NUM_SONGS
        bcc     @valid
        ldx     #$00
@valid:
        stx     song_idx

        ; Zero music state
        lda     #$00
        ldy     #(MUSIC_STATE_SIZE - 1)
@zero:  sta     MUSIC_STATE_ADDR,y
        dey
        bpl     @zero

        ; Initialize sound system
        jsr     sound_init

        ; Start requested song
        ldx     song_idx
        ldy     song_table,x
        jmp     music_start             ; tail call

song_idx:
        .byte   $00

; --- sid_play ---
; Called every frame (50Hz PAL) by the PSID driver.
sid_play:
        jmp     sound_update            ; tail call
